### ISSUE TITLE
minMeanCount lower boundary

### ISSUE THREAD

**Issue by bontus** [smithlabcode/riborex#2]
Dear all,

I have been wondering about your reasoning to hard-code the lower boundary of the "minMeanCount" parameter to 1, as it prevents me from running a consistent analysis (= using exactly the same transcriptome) when testing the effect of multiple different knock-outs on my cells (total of 4 KO vs. wild type pairs).
It is obviously possible to compare the results of each individual analysis, however, since the background set of genes is never fully the same, combining all different conditions into one overview table via cbind() is for instance not possible and extra effort is required to match the different result lists accordingly.
Since my analysis are based on DESeq2 and the issue of testing low count genes using DESeq2 has been discussed previously (see for instance [bioconductor mailing list](https://support.bioconductor.org/p/65256/)), I do not see any reason as to why "minMeanCount = 0" should not be allowed.

Kind regards

**Comment by wenzhenl** [comment]
Hi bontus,

We wanted to "use minMeanCount" to filter out those "unexpressed" genes. Although DESeq2 can handle the parameter estimation for "minMeanCount=0" for RNA-seq data, but  because we are dealing with both RNA- and Ribo-seq data, we were concerned that including "unexpressed" genes might affect the ratio of expression levels, so we took the conserved way to remove them before hand. Also, because riborex uses DESeq2, edgeR and Voom as engines, we need minMeanCount to be consistent for all three engines. 

For your problem, my understanding is that the gene lists you get in the result are not the same for different analysis because different genes are removed by minMeanCount, so you cannot compare them directly. If my understanding is right, I think you can easily put those "removed" genes back to the result gene list, I think I do have a R script somewhere for my own analysis, please let me know if you need it.

**Comment by bontus** [comment]
Hi wenzhenl,

Thank you for the swift response, I understand your concerns but AFAIK genes with 0 sums are assigned undefined values fold change and p-value by DESeq2, hence these should not affect the overall outcome. I have quickly tested the behavior when forcing minMeanCount=0 and the lists of significant genes are nearly identical for my data, so I think it is safe to say that at least DESeq2 seems to work fine regardless of filtering or not.
In the end, I think this issue boils down to whether the user should be able to take the decision or not. 
Hence, I would suggest to allow a lower threshold of 0, but to keep the current default (=1) and add a note about why it is recommended.

Best

**Comment by wenzhenl** [comment]
Hi bontus,

Thanks for the suggestion. I think you do have a point here. I will check more about how edgeR and Voom deal with the situation when minMeanCount=0 and see what I should do for the next release. 

thanks!
